/*
 * twinder
 * CS6650 assignment API
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.Objects;

/**
 * MatchStats
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-03-30T00:40:39.036945850Z[GMT]")
public class MatchStats {
  @SerializedName("numLikes")
  private Integer numLikes = null;

  @SerializedName("numDislikes")
  private Integer numDislikes = null;

  public MatchStats numLikes(Integer numLikes) {
    this.numLikes = numLikes;
    return this;
  }

   /**
   * Get numLikes
   * @return numLikes
  **/
  @Schema(example = "72", description = "")
  public Integer getNumLikes() {
    return numLikes;
  }

  public void setNumLikes(Integer numLikes) {
    this.numLikes = numLikes;
  }

  public MatchStats numDislikes(Integer numDislikes) {
    this.numDislikes = numDislikes;
    return this;
  }

   /**
   * Get numDislikes
   * @return numDislikes
  **/
  @Schema(example = "489", description = "")
  public Integer getNumDislikes() {
    return numDislikes;
  }

  public void setNumDislikes(Integer numDislikes) {
    this.numDislikes = numDislikes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MatchStats matchStats = (MatchStats) o;
    return Objects.equals(this.numLikes, matchStats.numLikes) &&
        Objects.equals(this.numDislikes, matchStats.numDislikes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numLikes, numDislikes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MatchStats {\n");
    
    sb.append("    numLikes: ").append(toIndentedString(numLikes)).append("\n");
    sb.append("    numDislikes: ").append(toIndentedString(numDislikes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
